apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: pet-clinic-e2e-ynljbravtp
    appstudio.openshift.io/component: quarkus-component-e2e-painjsgwpm
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: quarkus-component-e2e-painjsgwpm
  namespace: has-e2e-rwxp
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: quarkus-component-e2e-painjsgwpm
status:
  configuration:
    generatedName: ""
