apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: quarkus-component-e2e-lwyyarbgsu
  namespace: has-e2e-rwxp
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        appstudio.openshift.io/application: pet-clinic-e2e-ynljbravtp
        appstudio.openshift.io/component: quarkus-component-e2e-lwyyarbgsu
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: quarkus-component-e2e-lwyyarbgsu-
      labels:
        appstudio.openshift.io/application: pet-clinic-e2e-ynljbravtp
        appstudio.openshift.io/component: quarkus-component-e2e-lwyyarbgsu
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: has-e2e-rwxp
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:has-e2e-rwxp-quarkus-component-e2e-lwyyarbgsu-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/redhat-appstudio-qe/devfile-sample-code-with-quarkus/main/src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: ./
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          metadata:
            creationTimestamp: null
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
          status: {}
    status: {}
status: {}
